theme: 
  - osuny
  - osuny-plugin-centered-footer
_merge: deep
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/icon.svg'
  home:
    head:
      title: site